# config/application.yml
defaults: &defaults

development:
  <<: *defaults
# admin info
  admin_name: 'marcus'
  admin_email: 'marcuslin0724@gmail.com'
  admin_password: '11111111'
# admin email
  mail_ad: marcuslin0724@gmail.com
  mail_pw: 0972968663
# facebook
  facebook_id: '250816725069932'
  facebook_secret: '2acfc3ef37cb06125208f083d1dad765'

test:
  <<: *defaults

production:
  <<: *defaults