# config/application.yml
defaults: &defaults

development:
  <<: *defaults
# admin info
  admin_name: 'marcus'
  admin_email: 'bigheart.marcus@gmail.com'
  admin_password: 'marcus0972'
# admin email
  mail_ad: bigheart.marcus@gmail.com
  mail_pw: 0972968663
# facebook
  app_id: '250816725069932'
  secret: '2acfc3ef37cb06125208f083d1dad765'

test:
  <<: *defaults

production:
  <<: *defaults
# admin info
  admin_name: 'marcus'
  admin_email: 'bigheart.marcus@gmail.com'
  admin_password: '11111111'
# admin email
  mail_ad: bigheart.marcus@gmail.com
  mail_pw: 0972968663
# facebook
  app_id: '250816725069932'
  secret: '2acfc3ef37cb06125208f083d1dad765'