# config/application.yml
defaults: &defaults
  # admin info
    admin_name: 'marcus'
    admin_email: 'bigheart.marcus@gmail.com'
    admin_password: 'marcus0972'
  # admin email
    mail_ad: bigheart.marcus@gmail.com
    mail_pw: marcuslin0972

development:
  <<: *defaults
# facebook
  app_id: '472511292859137'
  secret: 'bb192c42c1120a7df8190abc62fb5b1a'
test:
  <<: *defaults

production:
  <<: *defaults
# facebook
  app_id: '250816725069932'
  secret: '2acfc3ef37cb06125208f083d1dad765'